CREATE VIEW [dbo].[VW_SIASUS] AS
SELECT
    CLASSE,
    PA_CODUNI,
	PA_UFMUN,
    DATA_PROCESSAMENTO,
    CAST(SUM(PA_QTDAPR) AS INT) AS QTD_APR,
    SUM(PA_VALAPR) AS VAL_APR
FROM SUS_SIASUS
GROUP BY 
    CLASSE,
    PA_CODUNI,
    DATA_PROCESSAMENTO,
	PA_UFMUN
GO
